from .empty import *
from .doorkey import *
from .multiroom import *
from .fetch import *
from .gotoobject import *
from .gotodoor import *
from .putnear import *
from .lockedroom import *
from .keycorridor import *
from .unlock import *
from .unlockpickup import *
from .blockedunlockpickup import *
from .playground_v0 import *
from .redbluedoors import *
from .obstructedmaze import *
from .memory import *
from .fourrooms import *
from .crossing import *
from .lavagap import *
from .dynamicobstacles import *
from .distshift import *
